NUM_GPU=1
torchrun --nnodes=1 --nproc_per_node=$NUM_GPU reverie/main_nav_obj.py \
--dataset reverie \
--output_dir ../../../vl_nav_output_reverie \
--world_size $NUM_GPU \
--seed 0 \
--tokenizer bert \
--num_pano_layers 2 \
--max_action_len 15 \
--max_objects 0 \
--max_instr_len 200 \
--batch_size 8 \
--lr 5e-5 \
--iters 20000 \
--log_every 1000 \
--optim adamW \
--expert_policy spl \
--train_alg dagger \
--ml_weight 0.2 \
--dagger_sample sample \
--feat_dropout 0.4 \
--dropout 0.5 \
--gamma 0. \
--features vitbase \
--image_feat_size 768 \
--obj_features vitbase \
--obj_feat_size 768 \
--angle_feat_size 4 \
--root_dir ../../build/duet
